[build]
target = "./index.html"
dist = "dist"

[serve]
port = 1420
open = false
ws_protocol = "ws"

[tools]
tailwindcss = "4.1.11"


[watch]
paths = ["src", "index.html", "../vedge-ui/src"]
