[package]
name = "pm-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.3", features = ["csr"] }
leptos_icons = "0.6.1"
leptos_router = "0.8.3"
reactive_stores = "0.2.5"
web-sys = { version = "0.3.77", features = ["HtmlElement", "Element", "Window", "Document", "DomRect", "MouseEvent"] }
