import Head from "next/head";
// import { Inter } from "next/font/google";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className=" text-3xl font-bold underline">Password Manager</h1>
        <div>
          <Link href="/login">
            <span className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">
              Login
            </span>
          </Link>
          <Link href="/vault">
            <span className="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">
              Vault
            </span>
          </Link>
        </div>

        <button className="rounded-full border border-purple-200 px-4 py-1 text-sm font-semibold text-purple-600 hover:border-transparent hover:bg-purple-600 hover:text-white focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2">
          Test
        </button>
      </main>
    </>
  );
}
