//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "theme")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub color_scheme_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::color_scheme::Entity",
        from = "Column::ColorSchemeId",
        to = "super::color_scheme::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    ColorScheme,
}

impl Related<super::color_scheme::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColorScheme.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
